databases:
  - name: stockgame-db
    databaseName: stockgame
    user: stockgame

services:
  - type: web
    name: stockgame-project
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stockgame-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: stockgame-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: stockgame-db
          property: password
      - key: ALPHAVANTAGE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: H2_CONSOLE
        value: "false"
